[package]
name = "microbit"
version = "0.1.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]

[lib]
crate-type = ["staticlib"]

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
features = ["mem"]
